---
abstract: 'REST Client Role'
author:
  - 'Kaare Rasmussen <kaare at cpan dot net>'
build_requires:
  Data::Serializer::JSON: '0'
  Data::Serializer::XML::Simple: '0'
  Data::Serializer::YAML: '0'
  File::Find: '0'
  File::Temp: '0'
  HTTP::Request: '0'
  HTTP::Thin: '0'
  JSON: '2.00'
  Module::Build: '0.3601'
  Moose: '0'
  Test::Deep: '0'
  Test::More: '0.88'
  XML::Simple: '0'
  YAML: '0'
  strict: '0'
  utf8: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Role-REST-Client
recommends:
  Data::Serializer::JSON: '0'
  Data::Serializer::XML::Simple: '0'
  Data::Serializer::YAML: '0'
  HTTP::Thin: '0'
  JSON: '2.00'
  XML::Simple: '0'
  YAML: '0'
requires:
  Carp: '0'
  Data::Serializer::Raw: '0'
  HTTP::Headers: '0'
  HTTP::Message: '0'
  HTTP::Response: '0'
  HTTP::Status: '0'
  HTTP::Thin: '0'
  HTTP::Tiny: '0'
  Moo: '1.003000'
  Moo::Role: '0'
  MooX::HandlesVia: '0.001004'
  Try::Tiny: '0'
  Type::Tiny: '0.024'
  Types::Standard: '0'
  URI::Escape::XS: '0.11'
resources:
  repository: git://github.com/kaare/Role-REST-Client.git
version: '0.18'
